import com.fy.export.util.IBshMapData;
import com.fy.export.util.DBUtil;
import com.fy.export.util.JdbcContext;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

/**
 * @author yinbin
 */
public class BshMapData implements IBshMapData {

	// 不要使用jdk1.5以上的语法
	// 比如：
	// 不要使用注解、泛型等
	public Map getMap() {
		Map map = new HashMap();
		String sql = "WITH zhubiao\n"
				+ "     AS (    SELECT cyhcode AS cprojectcode,\n"
				+ "                    cyhname AS cprojectname,\n"
				+ "                    cxmjytz AS jytz,\n"
				+ "                    iorder,\n"
				+ "                    cprojectname AS cprojectnamefmt,\n"
				+ "                    cstatus AS cstatus,\n"
				+ "                    parent_code,\n"
				+ "                    parent_name\n"
				+ "               FROM t_hig_szproject\n"
				+ "           ORDER BY iorder),\n"
				+ "     yz_jxje\n"
				+ "     AS (  SELECT cprojectcode,\n"
				+ "                  csxtypecode,\n"
				+ "                  'M' AS year_month,\n"
				+ "                  SUM (iyjmoney) AS jxje\n"
				+ "             FROM t_hig_borrow_jx\n"
				+ "            WHERE cstatus = 'Y' AND hig_report_borrow.fn_date ('M', djxenddate, TO_DATE ('2013-04-15', 'YYYY-MM-DD')) = 1\n"
				+ "         GROUP BY cprojectcode, csxtypecode\n"
				+ "         UNION ALL\n"
				+ "           SELECT cprojectcode,\n"
				+ "                  csxtypecode,\n"
				+ "                  'Y' AS year_month,\n"
				+ "                  SUM (iyjmoney) AS jxje\n"
				+ "             FROM t_hig_borrow_jx\n"
				+ "            WHERE cstatus = 'Y' AND hig_report_borrow.fn_date ('Y', djxenddate, TO_DATE ('2013-04-15', 'YYYY-MM-DD')) = 1\n"
				+ "         GROUP BY cprojectcode, csxtypecode\n"
				+ "         UNION ALL\n"
				+ "           SELECT cprojectcode,\n"
				+ "                  csxtypecode,\n"
				+ "                  'JD' AS year_month,\n"
				+ "                  NVL (SUM (iyjmoney), 0) AS jxje\n"
				+ "             FROM t_hig_borrow_jx\n"
				+ "            WHERE cstatus = 'Y'\n"
				+ "                  AND hig_report_borrow.fn_date ('JD', djxenddate, TO_DATE ('2013-04-15', 'YYYY-MM-DD')) = 1\n"
				+ "         GROUP BY cprojectcode, csxtypecode),\n"
				+ "     yz_yjlxys\n"
				+ "     AS (  SELECT t.cprojectcode,\n"
				+ "                  t.csxtypecode,\n"
				+ "                  'Y' AS year_month,\n"
				+ "                  NVL (SUM (t.iyjbudget), 0) AS yjlxys\n"
				+ "             FROM t_hig_rzbudget t\n"
				+ "            WHERE t.cstatus = 'Y' AND t.iyear = EXTRACT (YEAR FROM TO_DATE ('2013-04-15', 'YYYY-MM-DD'))\n"
				+ "         GROUP BY t.cprojectcode, t.csxtypecode\n"
				+ "         UNION ALL\n"
				+ "           SELECT t.cprojectcode,\n"
				+ "                  t.csxtypecode,\n"
				+ "                  'M' AS year_month,\n"
				+ "                  NVL (SUM (t.iyjbudget), 0) AS yjlxys\n"
				+ "             FROM t_hig_rzbudget t\n"
				+ "            WHERE     t.cstatus = 'Y'\n"
				+ "                  AND t.iyear = EXTRACT (YEAR FROM TO_DATE ('2013-04-15', 'YYYY-MM-DD'))\n"
				+ "                  AND t.imonth = EXTRACT (MONTH FROM TO_DATE ('2013-04-15', 'YYYY-MM-DD'))\n"
				+ "         GROUP BY t.cprojectcode, t.csxtypecode),\n"
				+ "     nofmt\n"
				+ "     AS (  SELECT cprojectcode,\n"
				+ "                  cprojectname,\n"
				+ "                  jytz,\n"
				+ "                  iorder,\n"
				+ "                  cprojectnamefmt,\n"
				+ "                  cstatus,\n"
				+ "                  cjbnlj,\n"
				+ "                  cjbylj,\n"
				+ "                  gdyjlxys,\n"
				+ "                  gdljyjlx,\n"
				+ "                  gdbnys,\n"
				+ "                  gdbnsj,\n"
				+ "                  gdbnc,\n"
				+ "                  gdbyys,\n"
				+ "                  gdbysj,\n"
				+ "                  gdbyc,\n"
				+ "                  kfyjlxys,\n"
				+ "                  kfljyjlx,\n"
				+ "                  kfbnys,\n"
				+ "                  kfbnsj,\n"
				+ "                  kfbnc,\n"
				+ "                  kfbyys,\n"
				+ "                  kfbysj,\n"
				+ "                  kfbyc,\n"
				+ "                  hjzjcblxzdtys,\n"
				+ "                  hjljyjlx,\n"
				+ "                  hjbnys,\n"
				+ "                  hjbnsj,\n"
				+ "                  hjbnc,\n"
				+ "                  hjbyys,\n"
				+ "                  hjbysj,\n"
				+ "                  hjbyc,\n"
				+ "                  parent_code,\n"
				+ "                  parent_name\n"
				+ "             FROM zhubiao\n"
				+ "         MODEL RETURN ALL ROWS\n"
				+ "            REFERENCE ref_jxje ON (SELECT * FROM yz_jxje)\n"
				+ "               DIMENSION BY (cprojectcode, csxtypecode, year_month)\n"
				+ "               MEASURES (jxje)\n"
				+ "            REFERENCE ref_yjlxys ON (SELECT * FROM yz_yjlxys)\n"
				+ "               DIMENSION BY (cprojectcode, csxtypecode, year_month)\n"
				+ "               MEASURES (yjlxys)\n"
				+ "         MAIN main_section\n"
				+ "            DIMENSION BY (cprojectcode, parent_code)\n"
				+ "            MEASURES ( cprojectname, jytz, iorder, cprojectnamefmt, cstatus, parent_name, 0 cjbnlj, 0 cjbylj, 0 gdljyjlx, 0 gdbnys, 0 gdbnsj, 0 gdbnc, 0 gdbyys, 0 gdbysj, 0 gdbyc, 0 kfljyjlx, 0 kfbnys, 0 kfbnsj, 0 kfbnc, 0 kfbyys, 0 kfbysj, 0 kfbyc, 0 gdyjlxys, 0 kfyjlxys, 0 hjzjcblxzdtys, 0 hjljyjlx, 0 hjbnys, 0 hjbnsj, 0 hjbnc, 0 hjbyys, 0 hjbysj, 0 hjbyc)\n"
				+ "             IGNORE NAV UNIQUE DIMENSION\n"
				+ "            RULES AUTOMATIC ORDER\n"
				+ "               (\n"
				+ "               cjbnlj [ANY, parent_code] =DECODE(cstatus[CV (), CV ()],'N',SUM(cjbnlj)[cprojectcode, CV (cprojectcode)],ref_jxje.jxje[CV (cprojectcode), 'CJ', 'Y']), --内部资金拆借利息 本年累计\n"
				+ "               cjbylj [ANY, parent_code] =DECODE(cstatus[CV (), CV ()],'N',SUM(cjbylj)[cprojectcode, CV (cprojectcode)],ref_jxje.jxje[CV (cprojectcode), 'CJ', 'M']), --内部资金拆借利息 本年累计\n"
				+ "               gdyjlxys [ANY, parent_code] =\n"
				+ "                     0,                                                                                             --股东 应计利息预算A' todo\n"
				+ "               gdljyjlx [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(gdljyjlx)[cprojectcode, CV (cprojectcode)],\n"
				+ "ref_jxje.jxje[CV (cprojectcode), 'GD', 'JD']), --股东投入应计利息 累计应计利息\n"
				+ "               gdbnys [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(gdbnys)[cprojectcode, CV (cprojectcode)],ref_yjlxys.yjlxys[CV (cprojectcode), 'GD', 'Y']),     --本年        预算\n"
				+ "               gdbnsj [ANY, parent_code] =\n"
				+ "               DECODE (cstatus[CV (), CV ()] ,'N',SUM(gdbnsj)[cprojectcode, CV (cprojectcode)], ref_jxje.jxje[CV (cprojectcode), 'GD', 'Y']),  --本年        实际\n"
				+ "               gdbnc [ANY, parent_code] =\n"
				+ "                       NVL (gdbnys[CV (), CV ()], 0)\n"
				+ "                     - NVL (gdbnsj[CV (), CV ()], 0),                           --本年        差\n"
				+ "               gdbyys [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(gdbyys)[cprojectcode, CV (cprojectcode)],ref_yjlxys.yjlxys[CV (cprojectcode), 'GD', 'M']),     --本月        预算\n"
				+ "               gdbysj [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(gdbysj)[cprojectcode, CV (cprojectcode)], ref_jxje.jxje[CV (cprojectcode), 'GD', 'M']),     --本月        实际\n"
				+ "               gdbyc [ANY, parent_code] =\n"
				+ "                       NVL (gdbyys[CV (), CV ()], 0)\n"
				+ "                     - NVL (gdbysj[CV (), CV ()], 0),                           --本月        差\n"
				+ "               kfyjlxys [ANY, parent_code] =\n"
				+ "                     0,                                                                                             --开发 应计利息预算A' todo\n"
				+ "               kfljyjlx [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(kfljyjlx)[cprojectcode, CV (cprojectcode)],ref_jxje.jxje[CV (cprojectcode), 'KF', 'JD']),    --开发贷应计利息                            \"累计应计利息\"\n"
				+ "               kfbnys [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(kfbnys)[cprojectcode, CV (cprojectcode)],ref_yjlxys.yjlxys[CV (cprojectcode), 'KF', 'Y']),          --本年        预算\n"
				+ "               kfbnsj [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(kfbnsj)[cprojectcode, CV (cprojectcode)],ref_jxje.jxje[CV (cprojectcode), 'KF', 'Y']),      --本年        实际\n"
				+ "               kfbnc [ANY, parent_code] =\n"
				+ "                       NVL (kfbnys[CV (), CV ()], 0)\n"
				+ "                     - NVL (kfbnsj[CV (), CV ()], 0),                           --本年        差\n"
				+ "               kfbyys [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N', SUM(kfbyys)[cprojectcode, CV (cprojectcode)],ref_yjlxys.yjlxys[CV (cprojectcode), 'KF', 'M']),              --本月        预算\n"
				+ "               kfbysj [ANY, parent_code] =\n"
				+ "               DECODE(cstatus[CV (), CV ()] ,'N',SUM(kfbysj)[cprojectcode, CV (cprojectcode)], ref_jxje.jxje[CV (cprojectcode), 'KF', 'M']),            --本月        实际\n"
				+ "               kfbyc [cprojectcode, parent_code] =\n"
				+ "                       NVL (kfbyys[CV (), CV ()], 0)\n"
				+ "                     - NVL (kfbysj[CV (), CV ()], 0),                         --本月        差\n"
				+ "               hjzjcblxzdtys [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdyjlxys[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfyjlxys[CV (), CV ()], 0),\n"
				+ "               hjljyjlx [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdljyjlx[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfljyjlx[CV (), CV ()], 0),                       --累计应计利息C=\n"
				+ "               hjbnys [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbnys[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbnys[CV (), CV ()], 0),                         --本年预算\n"
				+ "               hjbnsj [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbnsj[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbnsj[CV (), CV ()], 0),                         --本年实际\n"
				+ "               hjbnc [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbnc[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbnc[CV (), CV ()], 0),                           --本年差\n"
				+ "               hjbyys [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbyys[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbyys[CV (), CV ()], 0),                         --本月预算\n"
				+ "               hjbysj [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbysj[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbysj[CV (), CV ()], 0),                         --本月实际\n"
				+ "               hjbyc [cprojectcode, parent_code] =\n"
				+ "                       NVL (gdbyc[CV (), CV ()], 0)\n"
				+ "                     + NVL (kfbyc[CV (), CV ()], 0)                            --本月差\n"
				+ "                                                                                       )\n"
				+ "         ORDER BY  iorder)\n" + "SELECT cprojectcode,\n" + "       cprojectname,\n"
				+ "       jytz,\n" + "       iorder,\n" + "       cprojectnamefmt,\n" + "       cstatus,\n"
				+ "       cjbnlj,\n" + "       cjbylj,\n" + "       gdyjlxys,\n" + "       gdljyjlx,\n"
				+ "       gdbnys,\n" + "       gdbnsj,\n" + "       gdbnc,\n" + "       gdbyys,\n" + "       gdbysj,\n"
				+ "       gdbyc,\n" + "       kfyjlxys,\n" + "       kfljyjlx,\n" + "       kfbnys,\n"
				+ "       kfbnsj,\n" + "       kfbnc,\n" + "       kfbyys,\n" + "       kfbysj,\n" + "       kfbyc,\n"
				+ "       hjzjcblxzdtys,\n" + "       hjljyjlx,\n" + "       hjbnys,\n" + "       hjbnsj,\n"
				+ "       hjbnc,\n" + "       hjbyys,\n" + "       hjbysj,\n" + "       hjbyc,\n"
				+ "       TO_DATE ('2013-04-15', 'YYYY-MM-DD') AS cdate,\n" + "       'new' AS flag\n"
				+ "  FROM nofmt t";
		Connection con = null;
		try {
			con = JdbcContext.getJdbcConnection();
			map.put("list", DBUtil.queryMapList(con, sql));
			map.put("date", DBUtil.queryObject(con, "SELECT to_char(sysdate) FROM DUAL", String.class));
		} catch (Exception ex) {
			ex.printStackTrace();
		} finally {
			try {
				DBUtil.closeConnection(con);
			} catch (SQLException ex) {
				ex.printStackTrace();
			}
		}
		return map;
	}
}
